spring:
   rabbitmq:
    host: ${SECRET_CONFIG_RABBITMQ_HOST}
    port: ${SECRET_CONFIG_RABBITMQ_PORT}
    username: ${SECRET_CONFIG_RABBITMQ_USER}
    password: ${SECRET_CONFIG_RABBITMQ_PASSWORD}
   application:
    name: test_springbootms
myown:
    custom: test custom yaml
test.custom.message: Hello world I am the message number 2 modified 63